import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import ProviderComponent from '@/components/Provider'
import ProviderRedux from '@/components/ProviderRedux'
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ProviderComponent>
    <html lang="en">
      <body className={`${roboto.className} bg-gray-300`}>  
        <ProviderRedux>
          {children}
        </ProviderRedux>
      </body>
    </html>
    </ProviderComponent> 
  )
}
